time
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0002.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0003.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0004.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0005.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0006.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0008.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0009.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0010.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0011.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0012.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0013.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0014.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0015.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0016.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0017.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0018.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0019.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0020.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0021.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0022.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0023.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0024.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0025.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0026.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0027.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0028.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0029.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0030.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0031.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0032.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0033.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0034.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0035.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0036.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0037.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0038.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0039.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0040.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0041.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0042.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0043.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0044.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0045.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0046.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0047.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0048.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0049.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0050.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0051.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0052.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0053.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0054.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0055.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0056.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0057.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0058.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0060.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0061.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0062.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0063.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0064.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0065.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0066.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0067.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0068.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0069.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0070.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0071.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0072.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0073.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0074.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0075.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0076.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0077.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0078.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0079.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0080.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0081.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0082.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0083.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0084.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0085.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0086.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0087.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0088.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0089.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0090.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0091.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0092.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0093.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0094.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0095.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0096.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0097.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0098.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0099.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0100.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0101.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0102.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0103.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0104.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0105.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0106.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0107.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0108.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0109.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0110.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0111.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0112.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0113.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0114.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0115.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0116.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0118.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0120.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0121.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0122.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0123.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0124.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0125.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0126.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0127.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0128.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0129.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0130.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0131.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0132.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0134.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0135.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0136.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0137.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0138.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0139.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0140.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0141.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0142.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0143.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0144.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0146.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0147.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0148.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0149.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0150.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0151.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0152.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0153.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0154.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0155.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0156.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0157.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0158.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0159.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0160.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0161.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0162.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0163.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0164.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0165.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0166.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0167.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0168.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0169.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0170.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0171.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0172.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0173.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0174.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0175.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0176.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0177.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0178.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0179.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0180.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0181.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0183.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0184.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0185.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0186.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0187.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0188.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0189.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0191.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0194.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0195.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0196.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0197.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0198.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0199.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0200.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0201.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0202.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0203.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0204.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0205.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0206.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0208.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0209.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0210.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0211.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0212.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0213.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0214.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0215.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0216.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0217.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0218.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0219.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0220.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0221.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0222.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0223.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0224.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0225.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0226.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0227.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0228.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0229.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0230.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0231.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0232.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0233.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0234.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0235.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0236.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0237.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0238.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0239.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0240.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0241.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0242.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0243.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0244.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0245.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0246.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0247.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0248.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0249.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0250.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0251.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0252.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0253.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0254.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0255.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0256.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0257.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0258.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0259.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0260.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0261.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0262.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0263.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0264.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0265.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0266.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0267.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0268.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0269.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0271.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0272.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0273.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0274.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0275.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0277.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0278.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0279.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0280.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0281.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0282.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0283.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0284.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0285.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0286.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0287.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0288.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0289.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0290.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0291.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0292.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0293.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0294.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0295.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0296.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0297.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0298.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0299.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0300.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0301.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0302.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0303.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0304.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0305.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0306.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0307.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0308.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0310.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0311.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0312.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0313.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0314.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0315.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0316.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0318.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0319.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0320.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0321.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0322.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0323.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0324.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0327.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0328.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0329.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0330.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0331.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0332.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0335.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0336.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0341.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0342.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0343.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0344.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0345.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0346.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0348.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0349.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0350.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0351.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0352.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0353.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0354.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0355.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0356.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0357.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0358.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0359.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0360.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0361.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0362.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0363.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0364.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0367.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0368.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0369.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0370.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0371.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0372.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0373.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0374.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0375.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0376.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0377.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0378.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0379.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0380.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0381.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0382.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0383.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0384.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0385.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0386.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0387.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0388.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0389.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0390.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0391.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0392.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0393.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0394.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0395.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0396.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0397.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0398.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0399.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0400.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0401.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0402.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0403.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0404.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0405.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0406.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0407.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0410.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0411.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0412.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0413.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0414.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0415.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0416.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0417.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0418.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0419.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0420.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0421.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0422.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0423.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0425.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0426.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0427.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0428.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0430.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0431.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0432.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0433.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0434.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0435.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0437.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0438.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0439.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0440.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0441.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0442.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0443.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0444.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0445.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0446.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0447.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0448.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0449.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0450.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0451.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0452.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0453.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0454.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0455.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0456.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0457.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0458.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0459.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0460.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0461.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0462.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0463.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0464.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0465.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0466.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0467.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0468.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0469.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0470.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0471.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0472.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0474.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0475.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0476.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0477.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0478.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0479.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0480.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0481.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0482.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0483.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0484.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0485.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0486.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0487.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0488.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0489.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0490.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0491.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0492.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0493.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0494.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0495.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0496.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0497.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0498.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0499.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0500.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0501.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0502.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0503.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0504.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0505.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0507.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0509.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0510.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0511.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0512.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0513.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0514.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0515.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0516.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0517.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0518.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0519.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0520.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0521.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0522.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0523.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0525.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0526.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0527.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0528.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0529.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0530.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0531.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0532.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0533.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0534.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0535.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0536.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0537.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0538.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0539.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0540.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0541.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0542.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0543.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0544.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0545.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0546.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0547.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0548.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0549.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0550.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0551.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0552.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0553.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0554.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0555.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0556.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0558.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0559.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0560.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0561.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0562.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0563.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0564.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0565.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0566.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0567.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0568.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0569.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0570.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0571.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0572.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0573.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0574.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0575.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0577.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0578.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0579.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0580.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0581.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0582.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0583.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0584.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0585.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0586.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0587.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0588.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0589.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0590.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0591.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0592.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0593.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0594.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0595.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0596.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0597.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0598.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0599.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0600.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0601.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0602.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0604.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0605.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0606.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0607.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0608.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0609.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0610.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0611.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0612.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0613.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0614.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0615.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0616.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0617.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0618.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0619.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0620.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0621.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0622.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0623.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0624.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0625.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-0626.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-1010.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-1011.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-1012.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-1013.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-1014.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-1022.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-1023.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-1024.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-1025.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-1026.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-1027.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-1028.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-1029.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-1030.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-1031.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-1032.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-1033.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
python importcsv2postgres.py g:\transects\laz\metrics\NP_T-1034.CSV -s localhost -u postgres -p ebaeba18 -t metrics -d eba -sf 3 -nv -
time